# Generated by Django 5.2.7 on 2025-10-09 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_incident_latitude_remove_incident_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='ambulance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ambulance'),
        ),
        migrations.AddField(
            model_name='incident',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hospital'),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='driver',
            field=models.ForeignKey(limit_choices_to={'role': 'ambulance'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('available', 'Available'), ('busy', 'Busy')], default='idle', max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('reported', 'Reported'), ('assigned', 'Assigned'), ('completed', 'Completed')], default='reported', max_length=30),
        ),
    ]
