# Generated by Django 5.2.7 on 2025-10-10 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_role_incident_ambulance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organbank',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='ambulance',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='hospital',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='BloodBank',
        ),
        migrations.DeleteModel(
            name='OrganBank',
        ),
    ]
